version: '3.8'

services:
  app:
    image: 'docker-spring-boot-examen-swagger:latest'
    build:
      context: .
    container_name: app-examen-b
    depends_on:
      - db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=@Goldenboy2310@
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/db_examen_parcial_202120632
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=@Goldenboy2310@
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

    ports:
      - "6868:8080"
  db:
    image: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always
    container_name: db-examen-b
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=@Goldenboy2310@
      - POSTGRES_DB=db_examen_parcial_202120632
    ports:
      - "5433:5432"
volumes:
  db_data:
